### PR TITLE
Update to support GNU Radio 3.8

### PR DESCRIPTION
**Pull request by devnulling**
With these changes, qradiolink will build with GNU Radio 3.8/master.

I've tested the build on Ubuntu 18.04, using GR master, and the `gr3.8` branch of gr-osmosdr https://github.com/osmocom/gr-osmosdr/tree/gr3.8

In order to build the gr3.8 branch of gr-osmosdr, it is required to have >3.13 CMake installed (which has to be done from source on Ubuntu 18.04).

I haven't done extensive testing, but it streams and seems to work. 

qradio

When making these changes I found that the `MODE_700` that is called for in gr_{mod,demod}_base would throw an error, the change with https://github.com/qradiolink/qradiolink/commit/0d3b324a4a70a934fc9f0dafb1dda999835aa5b0 is mostly a hacky work around. This aspect needs a bit more attention/debugging.

### CODE REVIEW

**Comment by kantooon** [comment]
Good morning and thank you very much for the patchset! I've got two comments: mode 700D seems to have a problem on Debian Buster (stable) with segfaults and memory corruption inside libcodec2 - LDPC encode methods. For this reason, I've skipped this mode since I run Debian stable and use it as a base for the packages. Second, I will merge your changes to my gr_3.8_port branch instead of next, since Debian stable is still on 3.7. I will also rework the code to remove the MODE_700 code because that is indeed very hacky.
Thanks again!

**Comment by devnulling** [comment]
Also worth mentioning, I had built code2c/freedv from the latest source/master. 

I didn't really have much time to dig into the MODE_700 error, and just swapped it out for 700D so it'd compile.

**Comment by kantooon** [comment]
I've merged your changes into the gr_3.8_port branch of this repo. Next, I will have to set up a Travis build job for Debian testing which ships with GR 3.8 in order to build pakages based on it. Once Debian stable is updated, I will merge it into master.
Thanks again for the effort.

**Comment by kantooon** [comment]
The gr_3.8_port branch which contains these changes is now fully up to date with the latest changes in master and next, and some dependencies were added to enable building it on Debian 11 Bullseye. Some time in the next weeks, the gr 3.7 code will be frozen for maintenance and release branches and packages will be switched to GNU radio 3.8.

**Comment by kantooon** [comment]
I can't merge this as it is in the next branch, since there are too many conflicts. However, all your code is in gr_3.8_port and will soon enter next. Thanks for the effort.

**Pull request closed without merging**
