### PR TITLE
Add buildscript, de-hardcode lib flags, run protobuf on demand

### PR DESCRIPTION
**Pull request by marcusmueller**

### CODE REVIEW

**Comment by marcusmueller** [comment]
something's broken with the travis build - it expects files to be like upstream (which makes no sense when checking a PR).

**Comment by kantooon** [comment]
Sorry, Debian build is a little bit hardcoded to use the tags for version. Note to self, must fix that as well.

**Comment by kantooon** [comment]
There's a bit of a problem here, I believe removing the libs from the .pro file will break my build in QtCreator (which I use for convenience). I have to investigate how to set it up correctly on my side.

**Comment by marcusmueller** [comment]
Hm, you could make a copy of your specific .pro file and use that for internal development, or we could rewrite the build script to actually generate a .pro file. But doing the latter would practically amount to writing what CMake already is – a build system generator.

**Comment by kantooon** [comment]
I think I'll keep the libs in the .pro file for now if you don't mind, and aim to switch to CMake sooner. There are other people using QtCreator for building and debugging. Also, can I please ask to make pull requests agains the simplex branch, as it's used as a kind of 'next' staging area. Thanks.

**Comment by kantooon** [comment]
Closing this as no longer applicable. I think CMake will simply not happen, sorry.

**Pull request closed without merging**
